# Generated by Django 3.0.7 on 2020-07-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blocked_users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rey_reina',
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
