# Generated by Django 3.0.7 on 2020-07-19 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catmessage', '0002_juego'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='name',
        ),
        migrations.AddField(
            model_name='juego',
            name='all_choices',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='juego',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='juego',
            name='eight',
            field=models.CharField(default=0, max_length=63),
        ),
        migrations.AddField(
            model_name='juego',
            name='five',
            field=models.CharField(default=0, max_length=63),
        ),
        migrations.AddField(
            model_name='juego',
            name='four',
            field=models.CharField(default=0, max_length=63),
        ),
        migrations.AddField(
            model_name='juego',
            name='nine',
            field=models.CharField(default=0, max_length=63),
        ),
        migrations.AddField(
            model_name='juego',
            name='one',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='juego',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='juego',
            name='seven',
            field=models.CharField(default=0, max_length=63),
        ),
        migrations.AddField(
            model_name='juego',
            name='six',
            field=models.CharField(default=0, max_length=63),
        ),
        migrations.AddField(
            model_name='juego',
            name='three',
            field=models.CharField(default=0, max_length=63),
        ),
        migrations.AddField(
            model_name='juego',
            name='two',
            field=models.CharField(default=0, max_length=63),
        ),
    ]
