# Generated by Django 3.0.7 on 2020-07-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catmessage', '0003_auto_20200719_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='eight',
            field=models.CharField(choices=[('', 'seleciona aqui'), ('L', 'L'), ('E', 'E'), ('V', 'V')], default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='juego',
            name='five',
            field=models.CharField(choices=[('', 'seleciona aqui'), ('L', 'L'), ('E', 'E'), ('V', 'V')], default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='juego',
            name='four',
            field=models.CharField(choices=[('', 'seleciona aqui'), ('L', 'L'), ('E', 'E'), ('V', 'V')], default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='juego',
            name='nine',
            field=models.CharField(choices=[('', 'seleciona aqui'), ('L', 'L'), ('E', 'E'), ('V', 'V')], default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='juego',
            name='one',
            field=models.CharField(choices=[('', 'seleciona aqui'), ('L', 'L'), ('E', 'E'), ('V', 'V')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='juego',
            name='seven',
            field=models.CharField(choices=[('', 'seleciona aqui'), ('L', 'L'), ('E', 'E'), ('V', 'V')], default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='juego',
            name='six',
            field=models.CharField(choices=[('', 'seleciona aqui'), ('L', 'L'), ('E', 'E'), ('V', 'V')], default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='juego',
            name='three',
            field=models.CharField(choices=[('', 'seleciona aqui'), ('L', 'L'), ('E', 'E'), ('V', 'V')], default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='juego',
            name='two',
            field=models.CharField(choices=[('', 'seleciona aqui'), ('L', 'L'), ('E', 'E'), ('V', 'V')], default='', max_length=63),
        ),
    ]
