# Generated by Django 3.0.7 on 2020-08-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catmessage', '0004_auto_20200719_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='jornada',
            field=models.IntegerField(blank=True, default=4),
        ),
    ]
