# Generated by Django 3.0.7 on 2020-06-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maketip',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='maketip',
            name='info',
        ),
        migrations.RemoveField(
            model_name='maketip',
            name='likes',
        ),
        migrations.AddField(
            model_name='maketip',
            name='creativity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='maketip',
            name='outfit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='maketip',
            name='quality',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='maketip',
            name='sexy',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='maketip',
            name='post_pic',
            field=models.FileField(blank=True, help_text='Selecciona video', upload_to='media'),
        ),
    ]
