# Generated by Django 3.0.7 on 2020-06-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maketip',
            name='post_pic',
            field=models.TextField(),
        ),
    ]
