# Generated by Django 3.0.7 on 2020-06-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0002_auto_20200628_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='maketip',
            name='post_pict_link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='maketip',
            name='post_pic',
            field=models.FileField(blank=True, help_text='Selecciona video', null=True, upload_to='media'),
        ),
    ]
