# Generated by Django 3.0.7 on 2020-06-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0003_auto_20200628_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maketip',
            name='post_pic',
            field=models.URLField(null=True),
        ),
    ]
