# Generated by Django 3.0.7 on 2020-07-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0004_auto_20200628_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maketip',
            name='creativity',
        ),
        migrations.RemoveField(
            model_name='maketip',
            name='outfit',
        ),
        migrations.RemoveField(
            model_name='maketip',
            name='post_pic',
        ),
        migrations.RemoveField(
            model_name='maketip',
            name='post_pict_link',
        ),
        migrations.RemoveField(
            model_name='maketip',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='maketip',
            name='sexy',
        ),
        migrations.RemoveField(
            model_name='maketip',
            name='title',
        ),
        migrations.AddField(
            model_name='maketip',
            name='eight',
            field=models.CharField(default=0, max_length=63),
        ),
        migrations.AddField(
            model_name='maketip',
            name='five',
            field=models.CharField(default=0, max_length=63),
        ),
        migrations.AddField(
            model_name='maketip',
            name='four',
            field=models.CharField(default=0, max_length=63),
        ),
        migrations.AddField(
            model_name='maketip',
            name='nine',
            field=models.CharField(default=0, max_length=63),
        ),
        migrations.AddField(
            model_name='maketip',
            name='one',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='maketip',
            name='seven',
            field=models.CharField(default=0, max_length=63),
        ),
        migrations.AddField(
            model_name='maketip',
            name='six',
            field=models.CharField(default=0, max_length=63),
        ),
        migrations.AddField(
            model_name='maketip',
            name='three',
            field=models.CharField(default=0, max_length=63),
        ),
        migrations.AddField(
            model_name='maketip',
            name='two',
            field=models.CharField(default=0, max_length=63),
        ),
    ]
