# Generated by Django 3.0.7 on 2020-07-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0005_auto_20200713_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='maketip',
            name='all_choices',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
