# Generated by Django 3.0.7 on 2020-07-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0006_maketip_all_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='maketip',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
