# Generated by Django 3.0.7 on 2020-08-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0007_maketip_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='maketip',
            name='jornada',
            field=models.IntegerField(blank=True, default=4),
        ),
    ]
