# Generated by Django 3.0.7 on 2020-08-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0008_maketip_jornada'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True)),
            ],
        ),
    ]
