# Generated by Django 3.0.7 on 2020-08-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0009_jornadanum'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuegoJornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.IntegerField(blank=True, default=4)),
                ('p1', models.CharField(max_length=40)),
                ('p2', models.CharField(max_length=40)),
                ('p3', models.CharField(max_length=40)),
                ('p4', models.CharField(max_length=40)),
                ('p5', models.CharField(max_length=40)),
                ('p6', models.CharField(max_length=40)),
                ('p7', models.CharField(max_length=40)),
                ('p8', models.CharField(max_length=40)),
                ('p9', models.CharField(max_length=40)),
            ],
        ),
    ]
